name: build

on:
  push:
  pull_request:
  schedule:
    # because we're dependent on some docker images that can change
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image with tzdata embedded in go binary
      run: |
        docker build -t golang-scratch-test --pull .
        docker run --rm golang-scratch-test
    - name: Build the Docker image with tzdata from alpine
      run: |
        docker build -t golang-scratch-test-externaltz --pull -f Dockerfile.externaltz .
        docker run --rm golang-scratch-test-externaltz
